name: Build

on:
  push:
    branches: [ "**" ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-haskell@v1
    - name: Build
      run: ghc policy-format.hs

